services:
  muzi-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: muzi
      POSTGRES_PASSWORD: muzi
      POSTGRES_DB: Muzi
    ports:
      - 5432:5432
    volumes:
      - ./environments/docker/postgres/data:/var/lib/postgresql/data
    networks:
      - muzi
networks:
  muzi:
    name: muziNetwork
    driver: bridge
