name: pull_request_test

on:
  pull_request:
    branches:
      - '**'

jobs:
  testAndReport:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v2

      - name: PNPM 사용
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: NodeJS 설정
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: 의존성 설치
        run: pnpm i

      - name: Prisma Client 생성
        run: pnpm prisma:generate

      - name: 테스트 및 결과 저장
        run: pnpm test:ci

      - name: 리포트 생성
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: "테스트 결과 리포트"
          token: ${{ secrets.GITHUB_TOKEN }}
          path: junit.xml
          reporter: jest-junit
          fail-on-error: 'true'
